/**
 * Renders a trusted SVG string produced by @vector-create/core (or the server,
 * which itself calls core). The markup is generated by our own toolkit from a
 * bounded genome — not user free-text — so injecting it via innerHTML is safe.
 */
type Props = {
  svg: string;
  class?: string;
};

export function SvgFrame({ svg, class: className }: Props) {
  // The SVG is produced by our own core toolkit from a bounded genome (never
  // user free-text), so setting it as innerHTML is safe.
  return <div class={className} dangerouslySetInnerHTML={{ __html: svg }} />;
}
